easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields: 
                    - id
                    - name
                    - lastName
                    - email
                    - birthday
                    - sex                    
                    - { property: 'avatar', type: 'image', base_path: '/uploads/avatar' }
                    
            edit:
                fields:
                    - id
                    - name
                    - lastName
                    - email
                    - birthday
                    - sex
                    
    # ...
                
        Activity:
            class: App\Entity\Activity
            list:
                fields:
                    - id
                    - creator
                    - description
                    - category
                    - { property: 'pictures', type: 'image', base_path: '/uploads/picture' }
                    - prices
                    - tips
                    - address

            edit:
                fields:
                    - id
                    - creator
                    - description
                    - prices
                    - tips
                    - address

                    
        Advice:
            class: App\Entity\Advice
            list:
                fields:
                    - id
                    - registerDate
                    - message
                    - activityNotation
                    - adviceNotation
                    - activity
                    - user
 
            edit:
                fields:
                    - id
                    - registerDate
                    - message
                    - activityNotation
                    - adviceNotation
                    - activity
                    - user                    