easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields: 
                    - id
                    - name
                    - lastName
                    - { property: 'avatar', type: 'image', base_path: '/uploads/avatar' }
                
        Activity:
            class: App\Entity\Activity
            list:
                fields:
                    - id
                    - creator
                    - description
                    - category
                    - { property: 'pictures', type: 'image', base_path: '/uploads/picture' }
                    - prices
                    - tips
                    - address
                
        Advice:
            class: App\Entity\Advice
            list:
                fields:
                    - id
                    - activity_id
                    - user_id
                    - register_date
                    - message
                    - activity_notation
                    - advice_notation
                    